add watch operation

diff --git a/bin/k-get-jobs-sortedby-create b/bin/k-get-jobs-sortedby-create
--- a/bin/k-get-jobs-sortedby-create
+++ b/bin/k-get-jobs-sortedby-create
@@ -1,3 +1,26 @@
 #!/bin/sh
-set -xe
-kubectl get jobs --sort-by=.metadata.creationTimestamp
+while getopts ":wh" opt; do
+    case $opt in
+        w)
+            cmd="kubectl get jobs --sort-by=.metadata.creationTimestamp"
+            ;;
+        h)
+            echo "Usage: k-get-jobs-sortedby-create [-w]"
+            echo "List all jobs in the current namespace sorted by creation time"
+            echo "Options:"
+            echo "  -w  Watch the jobs"
+            exit 0
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            exit 1
+            ;;
+    esac
+done
+
+if [ $OPTIND -eq 1 ]; then
+    cmd="kubectl get jobs --sort-by=.metadata.creationTimestamp"
+fi
+
+echo $cmd
+$cmd
diff --git a/bin/k-get-pods-sortedby-create b/bin/k-get-pods-sortedby-create
--- a/bin/k-get-pods-sortedby-create
+++ b/bin/k-get-pods-sortedby-create
@@ -1,3 +1,25 @@
 #!/bin/sh
-set -xe
-kubectl get pods --sort-by=.metadata.creationTimestamp
+while getopts ":wh" opt; do
+    case $opt in
+        w)
+            cmd="kubectl get pods --sort-by=.metadata.creationTimestamp"
+        h)
+            echo "Usage: k-get-pods-sortedby-create [-w]"
+            echo "List all pods in the current namespace sorted by creation time"
+            echo "Options:"
+            echo "  -w  Watch the pods"
+            exit 0
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            exit 1
+            ;;
+    esac
+done
+
+if [ $OPTIND -eq 1 ]; then
+    cmd="kubectl get pods --sort-by=.metadata.creationTimestamp"
+fi
+
+echo $cmd
+$cmd
